input_data_path: "data/raw/heart.csv"
output_model_path: "models/model.pkl"
output_transformer_path: "models/transformer.pkl"
metric_path: "models/metrics.json"
splitting_params:
  val_size: 0.3
  random_state: 42
train_params:
  model_type: "LogisticRegression"
feature_params:
  categorical_features:
    - "cp"
    - "restecg"
    - "slope"
    - "ca"
    - "thal"
  numerical_features:
    - "age"
    - "trestbps"
    - "chol"
    - "thalach"
    - "oldpeak"
  binary_features:
    - "sex"
    - "fbs"
    - "exang"
  target_col: "target"