apiVersion: v1
kind: Pod
metadata:
  name: pod-resources
  labels:
    app: pod-resources
spec:
  containers:
    - image: yuliyademidova/online_inference:v1
      name: pod-resources
      ports:
        - containerPort: 8000
      resources:
        requests:
          memory: "128Mi"
          cpu: "200m"
        limits:
          memory: "500Mi"
          cpu: "500m"