apiVersion: v1
kind: Pod
metadata:
  name: simple-pod
  labels:
    app: fastapi-ml
spec:
  containers:
    - image: yuliyademidova/online_inference:v1
      name: fastapi-ml
      ports:
        - containerPort: 8000