apiVersion: v1
kind: Pod
metadata:
  name: pod-probes
  labels:
    app: fastapi-ml
spec:
  containers:
    - image: yuliyademidova/online_inference:v2
      name: fastapi-ml
      ports:
        - containerPort: 8000
      resources:
        requests:
          memory: "128Mi"
          cpu: "200m"
        limits:
          memory: "500Mi"
          cpu: "500m"
       readinessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 15
          periodSeconds: 5
       livenessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 15
            periodSeconds: 5
